// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFdshWMihgoxMx_xLv6vIodSyaQuVFiuo',
    appId: '1:941748750868:web:ccb6efcef04414cb97f501',
    messagingSenderId: '941748750868',
    projectId: 'raven-5b4bf',
    authDomain: 'raven-5b4bf.firebaseapp.com',
    databaseURL: 'https://raven-5b4bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raven-5b4bf.appspot.com',
    measurementId: 'G-D9B5DXZ4B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOtzpiVr8NE4yvb1Wz0tKnl_Lynt-rH0',
    appId: '1:941748750868:android:5b4a237519aec12297f501',
    messagingSenderId: '941748750868',
    projectId: 'raven-5b4bf',
    databaseURL: 'https://raven-5b4bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raven-5b4bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmpImKMi2qASu1E19pJ2bHZGkYEiAx-w',
    appId: '1:941748750868:ios:f22d2c5a10ee495397f501',
    messagingSenderId: '941748750868',
    projectId: 'raven-5b4bf',
    databaseURL: 'https://raven-5b4bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raven-5b4bf.appspot.com',
    iosClientId: '941748750868-atnlek0miq30888el3jujvb79c3ni0a1.apps.googleusercontent.com',
    iosBundleId: 'com.example.raven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVmpImKMi2qASu1E19pJ2bHZGkYEiAx-w',
    appId: '1:941748750868:ios:f22d2c5a10ee495397f501',
    messagingSenderId: '941748750868',
    projectId: 'raven-5b4bf',
    databaseURL: 'https://raven-5b4bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raven-5b4bf.appspot.com',
    iosClientId: '941748750868-atnlek0miq30888el3jujvb79c3ni0a1.apps.googleusercontent.com',
    iosBundleId: 'com.example.raven',
  );
}
