// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:9fe301f6dbf487a27c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-QEXYWW34MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpoCRJEsWxV6OkCa4vAsdLV7DiyEEwSM',
    appId: '1:254010117907:android:bb43bc3c526ec0617c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCX65x3IIGUN5JV9iLGaDGkCOgIjcWQo',
    appId: '1:254010117907:ios:ca4e187f036816227c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
    iosClientId: '254010117907-5qs6bf83v8hg83v6g71saoalib4fsquo.apps.googleusercontent.com',
    iosBundleId: 'com.example.raven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCX65x3IIGUN5JV9iLGaDGkCOgIjcWQo',
    appId: '1:254010117907:ios:ca4e187f036816227c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
    iosClientId: '254010117907-5qs6bf83v8hg83v6g71saoalib4fsquo.apps.googleusercontent.com',
    iosBundleId: 'com.example.raven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:b104a86f07835b337c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-Z9VG36KDLK',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:9fe301f6dbf487a27c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    databaseURL: 'https://raven-fef03-default-rtdb.firebaseio.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-QEXYWW34MJ',
  );
}
