// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:f7742c066a3d0ee07c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-WWB0H6GSES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpoCRJEsWxV6OkCa4vAsdLV7DiyEEwSM',
    appId: '1:254010117907:android:a484f7095f1963aa7c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    storageBucket: 'raven-fef03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCX65x3IIGUN5JV9iLGaDGkCOgIjcWQo',
    appId: '1:254010117907:ios:a5a67e3d4838f0487c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    storageBucket: 'raven-fef03.appspot.com',
    iosClientId: '254010117907-mjhgorg060ooulhtl665397f4668688k.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCX65x3IIGUN5JV9iLGaDGkCOgIjcWQo',
    appId: '1:254010117907:ios:a5a67e3d4838f0487c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    storageBucket: 'raven-fef03.appspot.com',
    iosClientId: '254010117907-mjhgorg060ooulhtl665397f4668688k.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:a4f65091b9317f917c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-6RZJLKBXW3',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBRkqbJrUaqRK6g1DVAPuQ1SkOjzfza2UM',
    appId: '1:254010117907:web:c2968baa7a52e2757c94e6',
    messagingSenderId: '254010117907',
    projectId: 'raven-fef03',
    authDomain: 'raven-fef03.firebaseapp.com',
    storageBucket: 'raven-fef03.appspot.com',
    measurementId: 'G-Q1WZDK48BK',
  );
}
